"use strict";
// This file is auto-generated by @hey-api/openapi-ts
var __assign = (this && this.__assign) || function () {
    __assign = Object.assign || function(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
                t[p] = s[p];
        }
        return t;
    };
    return __assign.apply(this, arguments);
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.createResourceSchema = exports.listResourceSchemas = exports.createBooking = exports.listBookings = exports.createSchema = exports.listSchemas = exports.createResource = exports.listResources = exports.readinessCheck = exports.healthCheck = exports.client = void 0;
var client_fetch_1 = require("@hey-api/client-fetch");
exports.client = (0, client_fetch_1.createClient)((0, client_fetch_1.createConfig)());
/**
 * Health check
 */
var healthCheck = function (options) {
    var _a;
    return ((_a = options === null || options === void 0 ? void 0 : options.client) !== null && _a !== void 0 ? _a : exports.client).get(__assign(__assign({}, options), { url: '/status/health' }));
};
exports.healthCheck = healthCheck;
/**
 * Readiness Check
 */
var readinessCheck = function (options) {
    var _a;
    return ((_a = options === null || options === void 0 ? void 0 : options.client) !== null && _a !== void 0 ? _a : exports.client).get(__assign(__assign({}, options), { url: '/status/ready' }));
};
exports.readinessCheck = readinessCheck;
/**
 * List Resources
 */
var listResources = function (options) {
    var _a;
    return ((_a = options === null || options === void 0 ? void 0 : options.client) !== null && _a !== void 0 ? _a : exports.client).get(__assign(__assign({}, options), { url: '/resources' }));
};
exports.listResources = listResources;
/**
 * Create resource
 */
var createResource = function (options) {
    var _a;
    return ((_a = options === null || options === void 0 ? void 0 : options.client) !== null && _a !== void 0 ? _a : exports.client).post(__assign(__assign({}, options), { url: '/resources' }));
};
exports.createResource = createResource;
/**
 * List Schemas
 */
var listSchemas = function (options) {
    var _a;
    return ((_a = options === null || options === void 0 ? void 0 : options.client) !== null && _a !== void 0 ? _a : exports.client).get(__assign(__assign({}, options), { url: '/schemas' }));
};
exports.listSchemas = listSchemas;
/**
 * Create schema
 */
var createSchema = function (options) {
    var _a;
    return ((_a = options === null || options === void 0 ? void 0 : options.client) !== null && _a !== void 0 ? _a : exports.client).post(__assign(__assign({}, options), { url: '/schemas' }));
};
exports.createSchema = createSchema;
/**
 * List Bookings
 */
var listBookings = function (options) {
    var _a;
    return ((_a = options === null || options === void 0 ? void 0 : options.client) !== null && _a !== void 0 ? _a : exports.client).get(__assign(__assign({}, options), { url: '/bookings' }));
};
exports.listBookings = listBookings;
/**
 * Create Booking
 */
var createBooking = function (options) {
    var _a;
    return ((_a = options === null || options === void 0 ? void 0 : options.client) !== null && _a !== void 0 ? _a : exports.client).post(__assign(__assign({}, options), { url: '/bookings' }));
};
exports.createBooking = createBooking;
/**
 * List resource schemas
 */
var listResourceSchemas = function (options) {
    var _a;
    return ((_a = options === null || options === void 0 ? void 0 : options.client) !== null && _a !== void 0 ? _a : exports.client).get(__assign(__assign({}, options), { url: '/resource-schemas' }));
};
exports.listResourceSchemas = listResourceSchemas;
/**
 * Create resource schema
 */
var createResourceSchema = function (options) {
    var _a;
    return ((_a = options === null || options === void 0 ? void 0 : options.client) !== null && _a !== void 0 ? _a : exports.client).post(__assign(__assign({}, options), { url: '/resource-schemas' }));
};
exports.createResourceSchema = createResourceSchema;
