// This file is auto-generated by @hey-api/openapi-ts

export const ModelSchema = {
    type: 'object',
    required: ['id', 'tenant_id', 'created_at', 'updated_at'],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        tenant_id: {
            type: 'string',
            example: 'acme'
        },
        created_at: {
            type: 'string',
            format: 'date-time'
        },
        updated_at: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const ResourceILoqDataSchema = {
    title: 'ResourceILoqData',
    type: 'object',
    required: ['calendar_id', 'network_module'],
    properties: {
        calendar_id: {
            type: 'string',
            description: 'refers to ILoq /api/v2/CalendarDataTitle'
        },
        network_module: {
            type: 'object',
            required: ['id', 'device_id', 'relay_id'],
            properties: {
                id: {
                    type: 'string',
                    description: 'refers to ILoq /api/v2/NetworkModule'
                },
                device_id: {
                    type: 'string',
                    description: 'refers to ILoq /api/v2/NetworkModuleDevice'
                },
                relay_id: {
                    type: 'string',
                    description: 'refers to ILoq /api/v2/NetworkModuleRelay'
                }
            }
        }
    }
} as const;

export const ResourceILoqSchema = {
    title: 'ResourceILoq',
    type: 'object',
    required: ['type', 'data'],
    properties: {
        type: {
            type: 'string',
            enum: ['iloq']
        },
        data: {
            '$ref': '#/components/schemas/ResourceILoqData'
        }
    }
} as const;

export const ResourceCreateRequestSchema = {
    title: 'ResourceCreateRequest',
    oneOf: [
        {
            '$ref': '#/components/schemas/ResourceILoq'
        }
    ],
    discriminator: {
        propertyName: 'type',
        mapping: {
            iloq: '#/components/schemas/ResourceILoq'
        }
    }
} as const;

export const ResourceSchema = {
    title: 'Resource',
    allOf: [
        {
            '$ref': '#/components/schemas/Model'
        },
        {
            '$ref': '#/components/schemas/ResourceCreateRequest'
        }
    ]
} as const;

export const ErrorSchema = {
    title: 'Error',
    type: 'object',
    required: ['message', 'request_id'],
    properties: {
        message: {
            type: 'string',
            example: 'error message'
        },
        description: {
            type: 'string',
            example: 'error description'
        },
        request_id: {
            type: 'string',
            example: 'PbMtZxrFhLNciaVMndIZkdQMHyiKUerV'
        }
    }
} as const;

export const SchemaSlotSchema = {
    title: 'SchemaSlot',
    type: 'object',
    required: ['from', 'to'],
    properties: {
        from: {
            type: 'string',
            description: `24h time of day without seconds, i.e "HH:mm".
hours > 24 allowed for timeslots that span
across midnight into the next day.
`,
            example: '04:00'
        },
        to: {
            type: 'string',
            description: `24h time of day without seconds, i.e "HH:mm".
hours > 24 allowed for timeslots that span
across midnight into the next day.
`,
            example: '06:00'
        }
    }
} as const;

export const SchemaRuleDailySchema = {
    title: 'SchemaRuleDaily',
    type: 'object',
    required: ['type', 'slots'],
    properties: {
        type: {
            type: 'string',
            enum: ['daily']
        },
        slots: {
            type: 'array',
            minItems: 1,
            maxItems: 1,
            items: {
                type: 'array',
                items: {
                    '$ref': '#/components/schemas/SchemaSlot'
                }
            }
        }
    }
} as const;

export const SchemaRuleWeeklySchema = {
    title: 'SchemaRuleDaily',
    type: 'object',
    required: ['type', 'slots'],
    properties: {
        type: {
            type: 'string',
            enum: ['weekly']
        },
        slots: {
            type: 'array',
            minItems: 7,
            maxItems: 7,
            items: {
                type: 'array',
                items: {
                    '$ref': '#/components/schemas/SchemaSlot'
                }
            }
        }
    }
} as const;

export const SchemaDataSchema = {
    title: 'SchemaData',
    oneOf: [
        {
            '$ref': '#/components/schemas/SchemaRuleDaily'
        },
        {
            '$ref': '#/components/schemas/SchemaRuleWeekly'
        }
    ],
    discriminator: {
        propertyName: 'type',
        mapping: {
            daily: '#/components/schemas/SchemaRuleDaily',
            weekly: '#/components/schemas/SchemaRuleWeekly'
        }
    }
} as const;

export const SchemaCreateRequestSchema = {
    title: 'SchemaCreateRequest',
    type: 'object',
    required: ['name', 'data'],
    properties: {
        name: {
            type: 'string',
            example: 'Tvättstugor'
        },
        data: {
            type: 'object',
            '$ref': '#/components/schemas/SchemaData'
        }
    }
} as const;

export const SchemaSchema = {
    title: 'Schema',
    type: 'object',
    allOf: [
        {
            '$ref': '#/components/schemas/Model'
        },
        {
            '$ref': '#/components/schemas/SchemaCreateRequest'
        }
    ]
} as const;

export const BookingCreateRequestSchema = {
    title: 'BookingCreateRequest',
    type: 'object',
    required: ['resource_id', 'booked_from', 'booked_to', 'booked_by', 'type'],
    properties: {
        resource_id: {
            type: 'string',
            format: 'uuid',
            description: 'The booked resource'
        },
        booked_from: {
            type: 'string',
            description: `24h time of day, i.e. "HH:mm".
hours > 24 are allowed to indicate that a time slot spans
across midnight and into the next day
`,
            example: '04:00'
        },
        booked_to: {
            type: 'string',
            pattern: '^\\d{2}:\\d{2}$',
            description: `24h time of day, i.e. "HH:mm".
hours > 24 are allowed to indicate that a time slot spans
across midnight and into the next day
`,
            example: '06:00'
        },
        booked_by: {
            type: 'string',
            description: `the party claiming the resource.
format may vary depending on resource type.
`
        },
        type: {
            type: 'string',
            enum: ['user', 'service-window']
        }
    }
} as const;

export const BookingSchema = {
    title: 'Booking',
    allOf: [
        {
            '$ref': '#/components/schemas/Model'
        },
        {
            '$ref': '#/components/schemas/BookingCreateRequest'
        }
    ]
} as const;

export const TenantConfigSchema = {
    title: 'TenantConfig',
    type: 'object'
} as const;

export const TenantSchema = {
    title: 'Tenant',
    type: 'object',
    required: ['id', 'created_at', 'updated_at', 'name', 'config'],
    properties: {
        id: {
            type: 'string',
            example: 'kruthusen'
        },
        created_at: {
            type: 'string',
            format: 'datetime'
        },
        updated_at: {
            type: 'string',
            format: 'datetime'
        },
        name: {
            type: 'string',
            example: 'ACME Inc.'
        },
        config: {
            '$ref': '#/components/schemas/TenantConfig'
        }
    }
} as const;