// This file is auto-generated by @hey-api/openapi-ts

export const ModelSchema = {
    type: 'object',
    required: ['id', 'tenant_id', 'created_at', 'updated_at'],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        tenant_id: {
            type: 'string',
            example: 'acme'
        },
        created_at: {
            type: 'string',
            format: 'date-time'
        },
        updated_at: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const ResourceILoqSchema = {
    title: 'ResourceILoq',
    type: 'object',
    required: ['type', 'calendar_id', 'network_module_id'],
    properties: {
        type: {
            type: 'string',
            enum: ['iloq']
        },
        calendar_id: {
            type: 'string',
            description: 'refers to ILoq /api/v2/CalendarDataTitle'
        },
        network_module_id: {
            type: 'string',
            description: 'refers to ILoq /api/v2/NetworkModule'
        },
        network_relay_id: {
            type: 'string',
            description: 'refers to ILoq /api/v2/NetworkModuleRelay'
        }
    }
} as const;

export const ResourceDataSchema = {
    title: 'ResourceData',
    oneOf: [
        {
            '$ref': '#/components/schemas/ResourceILoq'
        }
    ],
    discriminator: {
        propertyName: 'type',
        mapping: {
            iloq: '#/components/schemas/ResourceILoq'
        }
    }
} as const;

export const ResourceCreateRequestSchema = {
    title: 'ResourceCreateRequest',
    type: 'object',
    required: ['data'],
    properties: {
        data: {
            '$ref': '#/components/schemas/ResourceData'
        }
    }
} as const;

export const ResourceSchema = {
    title: 'Resource',
    allOf: [
        {
            '$ref': '#/components/schemas/Model'
        },
        {
            '$ref': '#/components/schemas/ResourceCreateRequest'
        }
    ]
} as const;

export const ErrorSchema = {
    title: 'Error',
    type: 'object',
    required: ['message', 'request_id'],
    properties: {
        message: {
            type: 'string',
            example: 'error message'
        },
        description: {
            type: 'string',
            example: 'error description'
        },
        request_id: {
            type: 'string',
            example: 'PbMtZxrFhLNciaVMndIZkdQMHyiKUerV'
        }
    }
} as const;

export const SchemaSlotSchema = {
    title: 'SchemaSlot',
    type: 'object',
    required: ['from', 'to'],
    properties: {
        from: {
            type: 'string',
            pattern: '^\\d{2}:\\d{2}$',
            description: `24 hour time.
`,
            example: '22:00'
        },
        to: {
            type: 'string',
            pattern: '^\\d{2}:\\d{2}$',
            description: `24 hour time.
hours > 24 are allowed.
`,
            example: '26:00'
        }
    }
} as const;

export const SchemaSlotsSchema = {
    title: 'SchemaSlots',
    type: 'array',
    oneOf: [
        {
            minItems: 1,
            maxItems: 1
        },
        {
            minItems: 7,
            maxItems: 7
        }
    ],
    items: {
        type: 'array',
        items: {
            '$ref': '#/components/schemas/SchemaSlot'
        }
    }
} as const;

export const SchemaCreateRequestSchema = {
    title: 'SchemaCreateRequest',
    type: 'object',
    required: ['name', 'type', 'slots'],
    properties: {
        name: {
            type: 'string',
            example: 'Tvättstugor'
        },
        type: {
            type: 'string',
            enum: ['daily', 'weekly']
        },
        slots: {
            '$ref': '#/components/schemas/SchemaSlots'
        }
    }
} as const;

export const SchemaSchema = {
    title: 'Schema',
    type: 'object',
    allOf: [
        {
            '$ref': '#/components/schemas/Model'
        },
        {
            '$ref': '#/components/schemas/SchemaCreateRequest'
        }
    ]
} as const;

export const BookingCreateRequestSchema = {
    title: 'BookingCreateRequest',
    type: 'object',
    required: ['resource_id', 'date', 'slot', 'booked_by', 'type'],
    properties: {
        resource_id: {
            type: 'string',
            format: 'uuid',
            description: 'The booked resource'
        },
        date: {
            type: 'string',
            pattern: '^\\d{4}-\\d{2}-\\d{2}$',
            description: 'ISO Date',
            example: '2024-01-01'
        },
        slot: {
            type: 'string',
            pattern: '^\\d{2}:\\d{2}$',
            description: `24 hour time specifier
`,
            example: '06:00'
        },
        booked_by: {
            type: 'string',
            description: `the party claiming the resource.
format may vary depending on resource type.
`
        },
        type: {
            type: 'string',
            enum: ['user', 'service-window']
        }
    }
} as const;

export const BookingSchema = {
    title: 'Booking',
    allOf: [
        {
            '$ref': '#/components/schemas/Model'
        },
        {
            '$ref': '#/components/schemas/BookingCreateRequest'
        }
    ]
} as const;

export const ResourceSchemaCreateRequestSchema = {
    title: 'ResourceSchemaCreateRequest',
    type: 'object',
    required: ['schema_id', 'resource_id', 'valid_from'],
    properties: {
        schema_id: {
            type: 'string',
            format: 'uuid'
        },
        resource_id: {
            type: 'string',
            format: 'uuid'
        },
        valid_from: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const ResourceSchemaSchema = {
    title: 'ResourceSchema',
    allOf: [
        {
            '$ref': '#/components/schemas/Model'
        },
        {
            '$ref': '#/components/schemas/ResourceSchemaCreateRequest'
        },
        {
            type: 'object',
            properties: {
                valid_to: {
                    type: 'string',
                    format: 'date-time'
                }
            }
        }
    ]
} as const;

export const TenantConfigSchema = {
    title: 'TenantConfig',
    type: 'object'
} as const;

export const TenantSchema = {
    title: 'Tenant',
    type: 'object',
    required: ['id', 'created_at', 'updated_at', 'name', 'config'],
    properties: {
        id: {
            type: 'string',
            example: 'kruthusen'
        },
        created_at: {
            type: 'string',
            format: 'datetime'
        },
        updated_at: {
            type: 'string',
            format: 'datetime'
        },
        name: {
            type: 'string',
            example: 'ACME Inc.'
        },
        config: {
            '$ref': '#/components/schemas/TenantConfig'
        }
    }
} as const;