// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type OptionsLegacyParser } from '@hey-api/client-fetch';
import type { HealthCheckError, HealthCheckResponse, ReadinessCheckError, ReadinessCheckResponse, ListResourcesError, ListResourcesResponse, CreateResourceData, CreateResourceError, CreateResourceResponse, ListSchemasError, ListSchemasResponse, CreateSchemaData, CreateSchemaError, CreateSchemaResponse, ListBookingsData, ListBookingsError, ListBookingsResponse, CreateBookingData, CreateBookingError, CreateBookingResponse, ListResourceSchemasData, ListResourceSchemasError, ListResourceSchemasResponse, CreateResourceSchemaData, CreateResourceSchemaError, CreateResourceSchemaResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Health check
 */
export const healthCheck = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<HealthCheckResponse, HealthCheckError, ThrowOnError>({
        ...options,
        url: '/status/health'
    });
};

/**
 * Readiness Check
 */
export const readinessCheck = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<ReadinessCheckResponse, ReadinessCheckError, ThrowOnError>({
        ...options,
        url: '/status/ready'
    });
};

/**
 * List Resources
 */
export const listResources = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<ListResourcesResponse, ListResourcesError, ThrowOnError>({
        ...options,
        url: '/resources'
    });
};

/**
 * Create resource
 */
export const createResource = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<CreateResourceData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateResourceResponse, CreateResourceError, ThrowOnError>({
        ...options,
        url: '/resources'
    });
};

/**
 * List Schemas
 */
export const listSchemas = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<ListSchemasResponse, ListSchemasError, ThrowOnError>({
        ...options,
        url: '/schemas'
    });
};

/**
 * Create schema
 */
export const createSchema = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<CreateSchemaData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateSchemaResponse, CreateSchemaError, ThrowOnError>({
        ...options,
        url: '/schemas'
    });
};

/**
 * List Bookings
 */
export const listBookings = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<ListBookingsData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListBookingsResponse, ListBookingsError, ThrowOnError>({
        ...options,
        url: '/bookings'
    });
};

/**
 * Create Booking
 */
export const createBooking = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<CreateBookingData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateBookingResponse, CreateBookingError, ThrowOnError>({
        ...options,
        url: '/bookings'
    });
};

/**
 * List resource schemas
 */
export const listResourceSchemas = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<ListResourceSchemasData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListResourceSchemasResponse, ListResourceSchemasError, ThrowOnError>({
        ...options,
        url: '/resource-schemas'
    });
};

/**
 * Create resource schema
 */
export const createResourceSchema = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<CreateResourceSchemaData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateResourceSchemaResponse, CreateResourceSchemaError, ThrowOnError>({
        ...options,
        url: '/resource-schemas'
    });
};